"""add pi_type field to PI

Revision ID: 06df15a0fb70
Revises: d4323fe451e7
Create Date: 2025-07-17 13:23:32.908235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06df15a0fb70'
down_revision = 'd4323fe451e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pi_type', sa.String(length=50), nullable=True))
        batch_op.alter_column('exporter_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('order_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_type', sa.VARCHAR(length=20), nullable=True))
        batch_op.alter_column('exporter_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('pi_type')

    # ### end Alembic commands ###
