"""add commission fields to PI

Revision ID: d4323fe451e7
Revises: f83b7468d2cd
Create Date: 2025-07-16 13:39:34.765950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4323fe451e7'
down_revision = 'f83b7468d2cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('commission_exporter_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('commission_factory_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('commission_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('commission_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('commission_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('factory_sale_amount', sa.Float(), nullable=True))
        batch_op.create_foreign_key(None, 'exporter', ['commission_exporter_id'], ['id'])
        batch_op.create_foreign_key(None, 'factory', ['commission_factory_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pi', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('factory_sale_amount')
        batch_op.drop_column('commission_status')
        batch_op.drop_column('commission_rate')
        batch_op.drop_column('commission_amount')
        batch_op.drop_column('commission_factory_id')
        batch_op.drop_column('commission_exporter_id')
        batch_op.drop_column('order_type')

    # ### end Alembic commands ###
