"""初始化数据库

Revision ID: f83b7468d2cd
Revises: 
Create Date: 2025-07-10 15:13:26.785743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f83b7468d2cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('tax_code', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('exporter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('tax_code', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('factory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('tax_code', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('freight_forwarder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('tax_code', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('packaging', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('freight_quote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('freight_forwarder_id', sa.Integer(), nullable=False),
    sa.Column('shipping_company', sa.String(length=100), nullable=False),
    sa.Column('departure_port', sa.String(length=100), nullable=False),
    sa.Column('destination_port', sa.String(length=100), nullable=False),
    sa.Column('route_type', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('quote_date', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=False),
    sa.Column('destination_14_days', sa.String(length=10), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['freight_forwarder_id'], ['freight_forwarder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pi_no', sa.String(length=50), nullable=False),
    sa.Column('pi_date', sa.Date(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('exporter_id', sa.Integer(), nullable=False),
    sa.Column('payment_terms', sa.String(length=100), nullable=True),
    sa.Column('loading_port', sa.String(length=100), nullable=True),
    sa.Column('destination_port', sa.String(length=100), nullable=True),
    sa.Column('bank', sa.Text(), nullable=True),
    sa.Column('shipment_date', sa.Date(), nullable=True),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('customer_name_snapshot', sa.String(length=100), nullable=True),
    sa.Column('customer_address_snapshot', sa.String(length=200), nullable=True),
    sa.Column('customer_tax_code_snapshot', sa.String(length=100), nullable=True),
    sa.Column('customer_country_snapshot', sa.String(length=50), nullable=True),
    sa.Column('customer_contact_snapshot', sa.String(length=100), nullable=True),
    sa.Column('customer_phone_snapshot', sa.String(length=50), nullable=True),
    sa.Column('customer_email_snapshot', sa.String(length=100), nullable=True),
    sa.Column('exporter_name_snapshot', sa.String(length=100), nullable=True),
    sa.Column('exporter_address_snapshot', sa.String(length=200), nullable=True),
    sa.Column('exporter_tax_code_snapshot', sa.String(length=100), nullable=True),
    sa.Column('exporter_country_snapshot', sa.String(length=50), nullable=True),
    sa.Column('exporter_contact_snapshot', sa.String(length=100), nullable=True),
    sa.Column('exporter_phone_snapshot', sa.String(length=50), nullable=True),
    sa.Column('exporter_email_snapshot', sa.String(length=100), nullable=True),
    sa.Column('freight_forwarder_id', sa.Integer(), nullable=True),
    sa.Column('ocean_freight', sa.Float(), nullable=True),
    sa.Column('container_date', sa.Date(), nullable=True),
    sa.Column('container_location', sa.String(length=100), nullable=True),
    sa.Column('etd', sa.Date(), nullable=True),
    sa.Column('eta', sa.Date(), nullable=True),
    sa.Column('coo_required', sa.String(length=10), nullable=True),
    sa.Column('apta_required', sa.String(length=10), nullable=True),
    sa.Column('export_license_required', sa.String(length=10), nullable=True),
    sa.Column('customs_docs_required', sa.String(length=10), nullable=True),
    sa.Column('other_documents', sa.String(length=200), nullable=True),
    sa.Column('bill_of_lading', sa.String(length=100), nullable=True),
    sa.Column('shipping_company', sa.String(length=100), nullable=True),
    sa.Column('coa_status', sa.String(length=20), nullable=True),
    sa.Column('insurance_status', sa.String(length=20), nullable=True),
    sa.Column('document_shipping_status', sa.String(length=20), nullable=True),
    sa.Column('tracking_number', sa.String(length=100), nullable=True),
    sa.Column('batch_no', sa.String(length=200), nullable=True),
    sa.Column('actual_departure_date', sa.Date(), nullable=True),
    sa.Column('vessel_info', sa.String(length=100), nullable=True),
    sa.Column('booking_number', sa.String(length=100), nullable=True),
    sa.Column('container_type_quantity', sa.String(length=20), nullable=True),
    sa.Column('shipping_mark', sa.String(length=50), nullable=True),
    sa.Column('freight_term', sa.String(length=50), nullable=True),
    sa.Column('contract_number', sa.String(length=100), nullable=True),
    sa.Column('freight_clause', sa.String(length=200), nullable=True),
    sa.Column('waybill_option', sa.String(length=50), nullable=True),
    sa.Column('container_number', sa.String(length=50), nullable=True),
    sa.Column('seal_number', sa.String(length=50), nullable=True),
    sa.Column('container_type', sa.String(length=20), nullable=True),
    sa.Column('quantity_units', sa.Float(), nullable=True),
    sa.Column('gross_weight', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('vgm', sa.String(length=50), nullable=True),
    sa.Column('total_quantity', sa.Float(), nullable=True),
    sa.Column('total_quantity_unit', sa.String(length=20), nullable=True),
    sa.Column('total_weight', sa.Float(), nullable=True),
    sa.Column('total_weight_unit', sa.String(length=20), nullable=True),
    sa.Column('total_volume', sa.Float(), nullable=True),
    sa.Column('total_volume_unit', sa.String(length=20), nullable=True),
    sa.Column('total_vgm', sa.String(length=50), nullable=True),
    sa.Column('actual_arrival_date', sa.Date(), nullable=True),
    sa.Column('payment_received', sa.String(length=10), nullable=True),
    sa.Column('freight_invoice_amount', sa.Float(), nullable=True),
    sa.Column('freight_invoice_confirmed', sa.String(length=10), nullable=True),
    sa.Column('freight_invoice_issued', sa.String(length=10), nullable=True),
    sa.Column('telex_release', sa.String(length=10), nullable=True),
    sa.Column('settlement_documents_required', sa.String(length=10), nullable=True),
    sa.Column('freight_payment_status', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['exporter_id'], ['exporter.id'], ),
    sa.ForeignKeyConstraint(['freight_forwarder_id'], ['freight_forwarder.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pi_no')
    )
    op.create_table('pi_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pi_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('factory_id', sa.Integer(), nullable=False),
    sa.Column('trade_term', sa.String(length=50), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('product_category_snapshot', sa.String(length=100), nullable=True),
    sa.Column('product_brand_snapshot', sa.String(length=100), nullable=True),
    sa.Column('product_model_snapshot', sa.String(length=100), nullable=True),
    sa.Column('product_packaging_snapshot', sa.String(length=100), nullable=True),
    sa.Column('factory_name_snapshot', sa.String(length=100), nullable=True),
    sa.Column('factory_address_snapshot', sa.String(length=200), nullable=True),
    sa.Column('factory_tax_code_snapshot', sa.String(length=100), nullable=True),
    sa.Column('factory_country_snapshot', sa.String(length=50), nullable=True),
    sa.Column('factory_contact_snapshot', sa.String(length=100), nullable=True),
    sa.Column('factory_phone_snapshot', sa.String(length=50), nullable=True),
    sa.Column('factory_email_snapshot', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['factory_id'], ['factory.id'], ),
    sa.ForeignKeyConstraint(['pi_id'], ['pi.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pi_item')
    op.drop_table('pi')
    op.drop_table('freight_quote')
    op.drop_table('user')
    op.drop_table('product')
    op.drop_table('freight_forwarder')
    op.drop_table('factory')
    op.drop_table('exporter')
    op.drop_table('customer')
    # ### end Alembic commands ###
