"""v2 clean baseline

Revision ID: v2_0001
Revises:
Create Date: 2026-08-21 21:44:43.575050
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'v2_0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('beneficiary_name', sa.String(length=200), nullable=False),
    sa.Column('bank_name', sa.String(length=200), nullable=False),
    sa.Column('bank_address', sa.Text(), nullable=True),
    sa.Column('account_number', sa.String(length=100), nullable=False),
    sa.Column('swift_code', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('remittance_information', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('tax_code', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('exporter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('tax_code', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('factory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('tax_code', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('freight_forwarder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('tax_code', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('packaging', sa.String(length=200), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('freight_quote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('freight_forwarder_id', sa.Integer(), nullable=False),
    sa.Column('shipping_company', sa.String(length=150), nullable=True),
    sa.Column('departure_port', sa.String(length=120), nullable=False),
    sa.Column('destination_port', sa.String(length=120), nullable=False),
    sa.Column('route_type', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('quote_date', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['freight_forwarder_id'], ['freight_forwarder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pi_no', sa.String(length=50), nullable=False),
    sa.Column('order_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('pi_date', sa.Date(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('exporter_id', sa.Integer(), nullable=True),
    sa.Column('commission_factory_id', sa.Integer(), nullable=True),
    sa.Column('customer_name_snapshot', sa.String(length=150), nullable=False),
    sa.Column('customer_address_snapshot', sa.Text(), nullable=True),
    sa.Column('customer_tax_code_snapshot', sa.String(length=100), nullable=True),
    sa.Column('customer_country_snapshot', sa.String(length=80), nullable=True),
    sa.Column('customer_contact_snapshot', sa.String(length=100), nullable=True),
    sa.Column('customer_phone_snapshot', sa.String(length=50), nullable=True),
    sa.Column('customer_email_snapshot', sa.String(length=150), nullable=True),
    sa.Column('exporter_name_snapshot', sa.String(length=150), nullable=True),
    sa.Column('exporter_address_snapshot', sa.Text(), nullable=True),
    sa.Column('exporter_tax_code_snapshot', sa.String(length=100), nullable=True),
    sa.Column('exporter_country_snapshot', sa.String(length=80), nullable=True),
    sa.Column('exporter_contact_snapshot', sa.String(length=100), nullable=True),
    sa.Column('exporter_phone_snapshot', sa.String(length=50), nullable=True),
    sa.Column('exporter_email_snapshot', sa.String(length=150), nullable=True),
    sa.Column('payment_terms', sa.String(length=200), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('advance_payment_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('advance_payment_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('advance_received_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('advance_received_at', sa.DateTime(), nullable=True),
    sa.Column('balance_payment_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('balance_received_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('balance_received_at', sa.DateTime(), nullable=True),
    sa.Column('loading_port', sa.String(length=100), nullable=True),
    sa.Column('destination_port', sa.String(length=100), nullable=True),
    sa.Column('planned_shipment_date', sa.Date(), nullable=True),
    sa.Column('bank_account_id', sa.Integer(), nullable=True),
    sa.Column('bank_beneficiary_snapshot', sa.String(length=200), nullable=True),
    sa.Column('bank_name_snapshot', sa.String(length=200), nullable=True),
    sa.Column('bank_address_snapshot', sa.Text(), nullable=True),
    sa.Column('bank_account_number_snapshot', sa.String(length=100), nullable=True),
    sa.Column('bank_swift_snapshot', sa.String(length=50), nullable=True),
    sa.Column('bank_currency_snapshot', sa.String(length=10), nullable=True),
    sa.Column('bank_remittance_snapshot', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('freight_forwarder_id', sa.Integer(), nullable=True),
    sa.Column('container_loading_at', sa.DateTime(), nullable=True),
    sa.Column('container_location', sa.String(length=200), nullable=True),
    sa.Column('driver_name', sa.String(length=100), nullable=True),
    sa.Column('driver_phone', sa.String(length=50), nullable=True),
    sa.Column('vehicle_number', sa.String(length=50), nullable=True),
    sa.Column('etd', sa.Date(), nullable=True),
    sa.Column('eta', sa.Date(), nullable=True),
    sa.Column('actual_departure_date', sa.Date(), nullable=True),
    sa.Column('actual_arrival_date', sa.Date(), nullable=True),
    sa.Column('coo_required', sa.Boolean(), nullable=True),
    sa.Column('apta_required', sa.Boolean(), nullable=True),
    sa.Column('export_license_required', sa.Boolean(), nullable=True),
    sa.Column('customs_docs_required', sa.Boolean(), nullable=True),
    sa.Column('coc_required', sa.Boolean(), nullable=True),
    sa.Column('coa_required', sa.Boolean(), nullable=True),
    sa.Column('original_bl_required', sa.Boolean(), nullable=True),
    sa.Column('obd_electronic_required', sa.Boolean(), nullable=True),
    sa.Column('insurance_original_required', sa.Boolean(), nullable=True),
    sa.Column('insurance_electronic_required', sa.Boolean(), nullable=True),
    sa.Column('original_documents_mail_required', sa.Boolean(), nullable=True),
    sa.Column('telex_release_required', sa.Boolean(), nullable=True),
    sa.Column('settlement_documents_required', sa.Boolean(), nullable=True),
    sa.Column('other_document_notes', sa.Text(), nullable=True),
    sa.Column('bill_of_lading_number', sa.String(length=100), nullable=True),
    sa.Column('shipping_company', sa.String(length=100), nullable=True),
    sa.Column('vessel_info', sa.String(length=100), nullable=True),
    sa.Column('booking_number', sa.String(length=100), nullable=True),
    sa.Column('shipping_mark', sa.String(length=100), nullable=True),
    sa.Column('freight_term', sa.String(length=50), nullable=True),
    sa.Column('contract_number', sa.String(length=100), nullable=True),
    sa.Column('freight_clause', sa.Text(), nullable=True),
    sa.Column('waybill_option', sa.String(length=30), nullable=True),
    sa.Column('container_type', sa.String(length=20), nullable=True),
    sa.Column('container_count', sa.Integer(), nullable=True),
    sa.Column('container_number', sa.String(length=100), nullable=True),
    sa.Column('seal_number', sa.String(length=100), nullable=True),
    sa.Column('package_count', sa.Integer(), nullable=True),
    sa.Column('package_unit', sa.String(length=20), nullable=True),
    sa.Column('gross_weight_kg', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('volume_cbm', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('vgm_kg', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('commission_rate', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('commission_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('commission_currency', sa.String(length=10), nullable=True),
    sa.Column('commission_amount_mode', sa.String(length=20), nullable=True),
    sa.Column('commission_override_reason', sa.Text(), nullable=True),
    sa.Column('commission_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("commission_amount_mode IS NULL OR commission_amount_mode IN ('DERIVED','EXPLICIT_OVERRIDE')", name='ck_pi_commission_mode'),
    sa.CheckConstraint("order_type IN ('SALES','COMMISSION')", name='ck_pi_order_type'),
    sa.CheckConstraint("status IN ('NEW','PRE_SHIPMENT','SHIPPED','ARRIVED','COMPLETED')", name='ck_pi_status'),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_account.id'], ),
    sa.ForeignKeyConstraint(['commission_factory_id'], ['factory.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['exporter_id'], ['exporter.id'], ),
    sa.ForeignKeyConstraint(['freight_forwarder_id'], ['freight_forwarder.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pi_no')
    )
    op.create_table('freight_settlement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pi_id', sa.Integer(), nullable=False),
    sa.Column('usd_bill_required', sa.Boolean(), nullable=True),
    sa.Column('usd_bill_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('usd_bill_confirmed', sa.Boolean(), nullable=True),
    sa.Column('cny_bill_required', sa.Boolean(), nullable=True),
    sa.Column('cny_bill_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cny_bill_confirmed', sa.Boolean(), nullable=True),
    sa.Column('invoice_issued', sa.Boolean(), nullable=True),
    sa.Column('invoice_issued_at', sa.DateTime(), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pi_id'], ['pi.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pi_id')
    )
    op.create_table('order_correction_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pi_id', sa.Integer(), nullable=False),
    sa.Column('module', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('opened_by_id', sa.Integer(), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('closed_by_id', sa.Integer(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('close_note', sa.Text(), nullable=True),
    sa.CheckConstraint("module IN ('COMMERCIAL','PAYMENT','DOCUMENTS','SHIPPING','FREIGHT','ARRIVAL')", name='ck_correction_module'),
    sa.ForeignKeyConstraint(['closed_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['opened_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['pi_id'], ['pi.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_correction_session_pi_id'), 'order_correction_session', ['pi_id'], unique=False)
    op.create_table('order_freight_agreement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pi_id', sa.Integer(), nullable=False),
    sa.Column('source_freight_quote_id', sa.Integer(), nullable=True),
    sa.Column('freight_forwarder_id', sa.Integer(), nullable=True),
    sa.Column('freight_forwarder_name_snapshot', sa.String(length=150), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('quote_date', sa.Date(), nullable=True),
    sa.Column('agreed_at', sa.DateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['freight_forwarder_id'], ['freight_forwarder.id'], ),
    sa.ForeignKeyConstraint(['pi_id'], ['pi.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_freight_quote_id'], ['freight_quote.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pi_id')
    )
    op.create_table('order_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pi_id', sa.Integer(), nullable=False),
    sa.Column('task_code', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('health', sa.String(length=20), nullable=False),
    sa.Column('completion_mode', sa.String(length=40), nullable=False),
    sa.Column('context_payload', sa.JSON(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('activation_at', sa.DateTime(), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('waiting_on', sa.String(length=40), nullable=True),
    sa.Column('waiting_since', sa.DateTime(), nullable=True),
    sa.Column('next_follow_up_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_by_id', sa.Integer(), nullable=True),
    sa.Column('resolution_code', sa.String(length=50), nullable=True),
    sa.Column('dedupe_key', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("health IN ('NORMAL','OVERDUE','EXCEPTION')", name='ck_task_health'),
    sa.CheckConstraint("status IN ('UPCOMING','ACTION','WAITING','DONE','CANCELLED')", name='ck_task_status'),
    sa.ForeignKeyConstraint(['completed_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['pi_id'], ['pi.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key', name='uq_order_task_dedupe_key')
    )
    op.create_index(op.f('ix_order_task_pi_id'), 'order_task', ['pi_id'], unique=False)
    op.create_table('pi_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pi_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('factory_id', sa.Integer(), nullable=True),
    sa.Column('trade_term', sa.String(length=20), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('quantity_unit', sa.String(length=20), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('product_category_snapshot', sa.String(length=100), nullable=True),
    sa.Column('product_brand_snapshot', sa.String(length=100), nullable=True),
    sa.Column('product_model_snapshot', sa.String(length=100), nullable=True),
    sa.Column('product_packaging_snapshot', sa.String(length=200), nullable=True),
    sa.Column('factory_name_snapshot', sa.String(length=150), nullable=True),
    sa.Column('factory_address_snapshot', sa.Text(), nullable=True),
    sa.Column('factory_tax_code_snapshot', sa.String(length=100), nullable=True),
    sa.Column('factory_country_snapshot', sa.String(length=80), nullable=True),
    sa.Column('factory_contact_snapshot', sa.String(length=100), nullable=True),
    sa.Column('factory_phone_snapshot', sa.String(length=50), nullable=True),
    sa.Column('factory_email_snapshot', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['factory.id'], ),
    sa.ForeignKeyConstraint(['pi_id'], ['pi.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pi_item_pi_id'), 'pi_item', ['pi_id'], unique=False)
    op.create_table('product_batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pi_item_id', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pi_item_id'], ['pi_item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pi_item_id', 'batch_number', name='uq_batch_item_number')
    )
    op.create_index(op.f('ix_product_batch_pi_item_id'), 'product_batch', ['pi_item_id'], unique=False)
    op.create_table('task_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('from_status', sa.String(length=20), nullable=True),
    sa.Column('to_status', sa.String(length=20), nullable=True),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['order_task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_activity_created_at'), 'task_activity', ['created_at'], unique=False)
    op.create_index(op.f('ix_task_activity_task_id'), 'task_activity', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_activity_task_id'), table_name='task_activity')
    op.drop_index(op.f('ix_task_activity_created_at'), table_name='task_activity')
    op.drop_table('task_activity')
    op.drop_index(op.f('ix_product_batch_pi_item_id'), table_name='product_batch')
    op.drop_table('product_batch')
    op.drop_index(op.f('ix_pi_item_pi_id'), table_name='pi_item')
    op.drop_table('pi_item')
    op.drop_index(op.f('ix_order_task_pi_id'), table_name='order_task')
    op.drop_table('order_task')
    op.drop_table('order_freight_agreement')
    op.drop_index(op.f('ix_order_correction_session_pi_id'), table_name='order_correction_session')
    op.drop_table('order_correction_session')
    op.drop_table('freight_settlement')
    op.drop_table('pi')
    op.drop_table('freight_quote')
    op.drop_table('user')
    op.drop_table('product')
    op.drop_table('freight_forwarder')
    op.drop_table('factory')
    op.drop_table('exporter')
    op.drop_table('customer')
    op.drop_table('bank_account')
    # ### end Alembic commands ###
